extends: standard
parserOptions:
  ecmaVersion: 8
  sourceType: 'module'
env:
  node: true
plugins:
  - promise
rules:
  no-console: 0
  no-return-await: 0
  arrow-parens: 0
  generator-star-spacing: 0
  no-debugger: 0